### ISSUE TITLE
Nullpointer exception when including a filter on message

### ISSUE THREAD

**Issue by diogonal** [handytecmobi/handytec-core#1]
There is a problem when executing a filtered message, on handytec.logic.domain.Update line 154, value = [null,null], so when you want to convert null to 'NULL' the null pointer exception is thrown.
Please have a try with the attached example message.
[R01_filtered.txt](https://github.com/handytecmobi/handytec-core/files/72871/R01_filtered.txt)

**Comment by juanalmeida** [comment]
Filter has to have operator:
	operatorMap.put("contains", "like");
	operatorMap.put("eq", "=");
	operatorMap.put("lt", "<");
	operatorMap.put("gt", ">");
	operatorMap.put("on", "=");
	operatorMap.put("before", "<");
	operatorMap.put("after", ">");
Fixed: If operator is not set, it puts by default equal.
